//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.ThermalCam
{
    [Serializable]
    public class ThermalCameraMsgMsg : Message
    {
        public const string k_RosMessageName = "thermal_cam/ThermalCameraMsg";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public float[] thermal_image;
        public const ushort WIDTH = 32;
        public const ushort HEIGHT = 24;

        public ThermalCameraMsgMsg()
        {
            this.header = new HeaderMsg();
            this.thermal_image = new float[0];
        }

        public ThermalCameraMsgMsg(HeaderMsg header, float[] thermal_image)
        {
            this.header = header;
            this.thermal_image = thermal_image;
        }

        public static ThermalCameraMsgMsg Deserialize(MessageDeserializer deserializer) => new ThermalCameraMsgMsg(deserializer);

        private ThermalCameraMsgMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.thermal_image, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.thermal_image);
            serializer.Write(this.thermal_image);
        }

        public override string ToString()
        {
            return "ThermalCameraMsgMsg: " +
            "\nheader: " + header.ToString() +
            "\nthermal_image: " + System.String.Join(", ", thermal_image.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
